
INSERT INTO company_admin (id, first_name, last_name, email, authority, city, version, username, password, phone_number, state,airline_id) VALUES (1, 'Alair', 'Sterke', 'asterke0@wordpress.com', 'AIRLINE_ADMIN', 'Idalolong', 0, 'airline_admin1', '$2a$10$NTB.lemL7k38r7aVGw65lOfRak53Lt9ihYJcR1wHFLm3v3Z2uNVTe', '946-448-3240', 'ACTIVE',1);
INSERT INTO company_admin (id, first_name, last_name, email, authority, city, version, username, password, phone_number, state,airline_id) VALUES (2, 'Eleen', 'Tadlow', 'etadlow1@prweb.com', 'AIRLINE_ADMIN', 'Sainte-Anne-de-Bellevue', 0, 'airline_admin2', '$2a$10$d0PDImL8wAvdHigzknF09.gcmpLKCv5SpoWAQ8nh1rdOxzrHIsi3e', '687-952-9012', 'ACTIVE',2);
INSERT INTO company_admin (id, first_name, last_name, email, authority, city, version, username, password, phone_number, state,airline_id) VALUES (3, 'Allys', 'Van Giffen', 'avangiffen2@blinklist.com', 'AIRLINE_ADMIN', 'Kiaranonggeng', 0, 'airline_admin3', '$2a$10$AHMaYB4k0smCSPHJ75mviOB4eO2JyaTmi3EEaYCZbJXetwXVZVxLm', '346-157-4231', 'ACTIVE',3);
/* Kreiranje admina hotela */
INSERT INTO company_admin (id, first_name, last_name, email, authority, city, version, username, password, phone_number, state,hotel_id) VALUES (4, 'Gun', 'Greenalf', 'ggreenalf0@goodreads.com', 'HOTEL_ADMIN', 'Antanifotsy', 0, 'hotel_admin1', '$2a$10$ndcc1ro1Jg6SesjjW3c7SunOceD5O55sz/WC9cV/0f7NeOSJ2.EhO', '712-713-6071', 'ACTIVE',1);
INSERT INTO company_admin (id, first_name, last_name, email, authority, city, version, username, password, phone_number, state,hotel_id) VALUES (5, 'Lilyan', 'Bowsher', 'lbowsher1@google.ru', 'HOTEL_ADMIN', 'Nangkasari', 0, 'hotel_admin2', '$2a$10$BozJ6jzk3aCMgGIN7cFOju1my62Mc51CW/isE110tey1/JN7jaTIW', '183-882-4889', 'ACTIVE',2);
INSERT INTO company_admin (id, first_name, last_name, email, authority, city, version, username, password, phone_number, state,hotel_id) VALUES (6, 'Orlan', 'Midford', 'omidford2@360.cn', 'HOTEL_ADMIN', 'Derbent', 0, 'hotel_admin3', '$2a$10$Uj5f.2lY.XoKqPbPo2COiOLLLLnG8pTvYg4I.fsbcrn9pIOImpAGu', '450-147-6406', 'ACTIVE',3);
/* Kreiranje admina rent-a-car-a */
INSERT INTO company_admin (id, first_name, last_name, email, authority, city, version, username, password, phone_number, state,rentacar_id) VALUES (7, 'Rafaello', 'Pepis', 'rpepis0@pbs.org', 'RENT_A_CAR_ADMIN', 'Leninsk', 0, 'rent_admin1', '$2a$10$l32J3RJHr7kH6KP6vmDmou3wtP0/bROwHxROe/q6Rj3ILV9cRYi6q', '237-261-4660', 'ACTIVE',1);
INSERT INTO company_admin (id, first_name, last_name, email, authority, city, version, username, password, phone_number, state,rentacar_id) VALUES (8, 'Orlando', 'Mulvagh', 'omulvagh1@usnews.com', 'RENT_A_CAR_ADMIN', 'Cedynia', 0, 'rent_admin2', '$2a$10$E5Vsa4Debcmsi0gRkzHiauJ2yF8bVcit58JP2EciJ5UHe1jagH4Bi', '710-547-6466', 'ACTIVE',1);
INSERT INTO company_admin (id, first_name, last_name, email, authority, city, version, username, password, phone_number, state,rentacar_id) VALUES (9, 'Korrie', 'Ricciardelli', 'kricciardelli2@godaddy.com', 'RENT_A_CAR_ADMIN', 'Angers', 0, 'rent_admin3', '$2a$10$Cj8.2Iex2MF3uDGgBKbXY.Rth.SXPAehCYDB0oVQ9OfCa4VdzvlWK', '303-148-6796', 'ACTIVE',3);
/* Kreiranje admina sistema */
INSERT INTO user_admin (id, first_name, last_name, email, authority, city, version, username, password, phone_number, state) VALUES (10, 'Lorelle', 'Pevreal', 'lpevreal0@studiopress.com', 'USERS_ADMIN', 'Santa Cruz', 0, 'admin', '$2a$10$jWsfQV4OfLEOlfz64gmyTuY0M4Mtmcjp0SRaBST6M3b0lh2dGKTIa', '140-456-6046', 'ACTIVE');